CREATE TABLE IF NOT EXISTS FOLLOWERS (
  ID INTEGER PRIMARY KEY,
  USER_ID INTEGER NOT NULL,
  FOLLOWER_ID INTEGER NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  FOREIGN KEY (FOLLOWER_ID) REFERENCES USERS(ID)
);
