CREATE TABLE IF NOT EXISTS RETWEET (
  ID INTEGER PRIMARY KEY,
  USER_ID INTEGER,
  GWEET_ID INTEGER,
  RETWEET_BY INTEGER,
  FOREIGN KEY (GWEET_ID) REFERENCES Tweets(id),
  FOREIGN KEY (RETWEET_BY) REFERENCES Tweets(id)
);
