CREATE TABLE IF NOT EXISTS RETWEET (
  USER_ID INTEGER NOT NULL,
  GWEET_ID INTEGER NOT NULL,
  RETWEET_BY INTEGER NOT NULL,

  PRIMARY KEY (USER_ID, GWEET_ID),
  FOREIGN KEY (GWEET_ID) REFERENCES GTEETS(id),
  FOREIGN KEY (RETWEET_BY) REFERENCES GTWEETS(id)
);
