DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS
(
    ID       INTEGER PRIMARY KEY AUTOINCREMENT  NOT NULL,
    GWEET_ID INTEGER                            NOT NULL,
    USER_ID  INTEGER                            NOT NULL,
    COMMENT  TEXT                               NOT NULL,
    DATE     DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (GWEET_ID)
        REFERENCES GWEETS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
