DROP TABLE IF EXISTS FOLLOWERS;

CREATE TABLE FOLLOWERS
(
    ID          INTEGER PRIMARY KEY NOT NULL,
    USER_ID     INTEGER             NOT NULL,
    FOLLOWER_ID INTEGER             NOT NULL,

    FOREIGN KEY (FOLLOWER_ID)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);