DROP TABLE IF EXISTS FOLLOWINGS;

CREATE TABLE FOLLOWINGS
(
    ID           INTEGER PRIMARY KEY NOT NULL,
    USER_ID      INTEGER             NOT NULL,
    FOLLOWING_ID INTEGER             NOT NULL,

    FOREIGN KEY (FOLLOWING_ID)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
