DROP TABLE IF EXISTS GWEETS;

CREATE TABLE GWEETS
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT  NOT NULL,
    USER_ID     INTEGER                            NOT NULL,
    CAPTION     TEXT                               NOT NULL,
    VIEW_COUNT  INTEGER                            NOT NULL,
    POSTED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,

    FOREIGN KEY (USER_ID)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CHECK ( VIEW_COUNT >= 0 )
);