DROP TABLE IF EXISTS LIKES;

CREATE TABLE LIKES
(
    ID       INTEGER PRIMARY KEY NOT NULL,
    GWEET_ID INTEGER             NOT NULL,
    LIKED_BY INTEGER             NOT NULL,
    FOREIGN KEY (LIKED_BY)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (GWEET_ID)
        REFERENCES GWEETS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);