DROP TABLE IF EXISTS REPOST;

CREATE TABLE REPOST
(
    ID        INTEGER PRIMARY KEY NOT NULL,
    REPOST_BY INTEGER             NOT NULL,
    GWEET_ID  INTEGER             NOT NULL,

    FOREIGN KEY (REPOST_BY)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (GWEET_ID)
        REFERENCES GWEETS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);