DROP TABLE IF EXISTS SHARE;

CREATE TABLE SHARE
(
    ID        INTEGER PRIMARY KEY NOT NULL,
    GWEET_ID  INTEGER             NOT NULL,
    SHARED_BY INTEGER             NOT NULL,

    FOREIGN KEY (SHARED_BY)
        REFERENCES USERS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (GWEET_ID)
        REFERENCES GWEETS (ID)
        ON UPDATE CASCADE
        ON DELETE CASCADE

);