DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS
(
    ID        INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NAME      TEXT                              NOT NULL,
    PASSWORD  VARCHAR(20)                       NOT NULL,
    JOINED_ON DATE DEFAULT CURRENT_TIMESTAMP    NOT NULL,

    CHECK ( length(PASSWORD) >= 6 )
);