INSERT INTO Users (UserName, Password, FullName, Bio) VALUES
("sulabhghimire",  "sulabhadmin", "Sulabh Ghimire", "Hello, I am an engineering student"),
("sagarsubedi",  "sagaradmin", "Sagar Subedi", "Hello, I am a actor"),
("sureshsir",  "sureshadmin", "Suresh Panth", "Hello, I am a cyver security student"),
("drddesign",  "dayaadmin", "Daya Raj Dhungana", "Hello, I am a designing student and a CR"),
("anupak",  "anupadmin", "Anup Adhikari", "Hello, I am a project management student"),
("modernbib",  "bibekadmin", "Bibek Chalise", "Hello, I am an AI and machine learning student"),
("shushiljinx",  "shushiladmin", "Shushil Poudel", "Hello, I am a rich student"),
("eldringrg",  "eldrinadmin", "Eldrin Gurung", "Hello, I am an overall knowledge student"),
("prashantpnt",  "prashantadmin", "Prashant Pant", "Hello, I am a devotee student"),
("krishna",  "krishnaadmin", "Krishna Parsad Tamang", "Hello, I am an old student");

INSERT INTO Posts (UserID, content) VALUES
(1, "Engineering is the use of scientific principles to design and build machines, structures, and other items, including bridges, tunnels, roads, vehicles, and buildings.[1] The discipline of engineering encompasses a broad range of more specialized fields of engineering, each with a more specific emphasis on particular"),
(1, "Engineering has existed since ancient times, when humans devised inventions such as the wedge, lever, wheel and pulley, etc."),
(2, "Kush developed the Sakia during the 4th century BC, which relied on animal power instead of human energy."),
(2, "The earliest practical wind-powered machines, the windmill and wind pump, first appeared in the Muslim world during the Islamic Golden Age, in what are now Iran, Afghanistan, and Pakistan, by the 9th century AD."),
(3, "The science of classical mechanics, sometimes called Newtonian mechanics, formed the scientific basis of much of modern engineering."),
(3, "Canal building was an important engineering work during the early phases of the Industrial Revolution."),
(4, "Applied science lead to the development of the steam engine."),
(4, "The application of steam-powered cast iron blowing cylinders for providing pressurized air for blast furnaces lead to a large increase in iron production in the late 18th century."),
(5, "The Industrial Revolution created a demand for machinery with metal parts, which led to the development of several machine tools."),
(5, "Boring cast iron cylinders with precision was not possible until John Wilkinson invented his boring machine, which is considered the first machine tool."),
(6, "Other machine tools included the screw cutting lathe, milling machine, turret lathe and the metal planer."),
(6, "Precision machining techniques were developed in the first half of the 19th century."),
(7, "Machine tools and machining techniques capable of producing interchangeable parts lead to large scale factory production by the late 19th century."),
(7, "Aeronautical engineering deals with aircraft design process design while aerospace engineering is a more modern term that expands the reach of the discipline by including spacecraft design."),
(8, "Engineering is a broad discipline that is often broken down into several sub-disciplines. "),
(8, "hemical engineering is the application of physics, chemistry, biology, and engineering principles in order to carry out chemical processes on a commercial scale."),
(9, "Bioengineering is the engineering of biological systems for a useful purpose."),
(9, "Examples of bioengineering research include bacteria engineered to produce chemicals, new medical imaging technology, portable and rapid disease diagnostic devices, prosthetics, biopharmaceuticals, and tissue-engineered organs."),
(10, "Aerospace engineering covers the design, development, manufacture and operational behaviour of aircraft, satellites and rockets."),
(10, "Computer engineering (CE) is a branch of engineering that integrates several fields of computer science and electronic engineering required to develop computer hardware and software.");

INSERT INTO Connection (WhoID, WhomID) VALUES
(1,2),
(1,3),
(1,10),
(2,1),
(2,5),
(2,10),
(3,4),
(3,6),
(3,8),
(4,2),
(4,5),
(4,9),
(5,1),
(5,4),
(5,7),
(5,10),
(6,2),
(6,5),
(6,7),
(6,10),
(7,3),
(7,8),
(8,1),
(8,5),
(8,10),
(9,4),
(9,10),
(9, 2),
(10,1),
(10,9),
(10,8);