CREATE TABLE IF NOT EXISTS Users(
   UserID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
   UserName VARCHAR(20) NOT NULL UNIQUE,
   Password TEXT NOT NULL CHECK (length(Password) >=8),
   FullName TEXT NOT NULL,
   Bio TEXT 
);

CREATE TABLE IF NOT EXISTS Posts(
    PostID INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    content TEXT NOT NULL,
    FOREIGN KEY (UserID)
        REFERENCES Users (UserID)
            ON UPDATE NO ACTION
            ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Connection(
    WhoID INTEGER NOT NULL,
    WhomID INTEGER NOT NULL,
    PRIMARY KEY (WhoID, WhomID),
    UNIQUE (WhoID, WhomID),
    FOREIGN KEY (WhoID)
        REFERENCES Users(UserID)
            ON UPDATE NO ACTION
            ON DELETE CASCADE,
    FOREIGN KEY (WhomID)
        REFERENCES Users(UserID)
            ON UPDATE NO ACTION
            ON DELETE CASCADE
);