-- DISPLAY THE TOP FIVE USERS
SELECT *
FROM USERS
LIMIT 5;

-- DISPLAY THE TOP FIVE GWEETS
SELECT *
FROM GWEETS
LIMIT 5;

-- DISPLAY THE COMMENTS OF GWEET ID = 1
SELECT COMMENT
FROM COMMENTS
WHERE COMMENTS.GWEET_ID = 1;

-- SHOW THE ALL THE GWEET DONE BY USER jtomblings0
SELECT G.CAPTION
FROM GWEETS G
WHERE G.USER_ID = (SELECT ID
                   FROM USERS U
                   WHERE U.NAME = 'jtomblings0');

-- Display the count of likes and repost of Gweet with id 100
SELECT count(*)
from LIKES
WHERE LIKES.GWEET_ID = 100;

SELECT count(*)
from REPOST
WHERE REPOST.GWEET_ID = 100;

