-- DISPLAY THE TOP FIVE USERS
SELECT *
FROM USERS
LIMIT 5;

-- DISPLAY THE TOP FIVE GWEETS
SELECT *
FROM GWEETS
LIMIT 5;

-- DISPLAY THE COMMENTS OF GWEET ID = 1
SELECT COMMENT
FROM COMMENTS
WHERE GWEET_ID = 1;

-- SHOW ALL THE GWEET DONE BY USER jtomblings0
SELECT G.CAPTION
FROM GWEETS G
JOIN USERS U ON G.USER_ID = U.ID
WHERE U.NAME = 'jtomblings0';

-- Display the count of likes and repost of Gweet with id 100
SELECT (SELECT COUNT(*) FROM LIKES WHERE GWEET_ID = 100) AS LikesCount,
       (SELECT COUNT(*) FROM REPOST WHERE GWEET_ID = 100) AS RepostCount;
