

-- Insert statements
INSERT INTO RETWEET (ID, RETWEET_BY, GWEET_ID) VALUES (1, 81, 11);
INSERT INTO RETWEET (ID, RETWEET_BY, GWEET_ID) VALUES (2, 4, 27);
INSERT INTO RETWEET (ID, RETWEET_BY, GWEET_ID) VALUES (3, 59, 34);
-- ... add more INSERT statements here

