

-- Insert statements
INSERT INTO LIKES (id, GWEET_ID, LIKED_BY) VALUES (1, 100, 51);
INSERT INTO LIKES (id, GWEET_ID, LIKED_BY) VALUES (2, 10, 56);
INSERT INTO LIKES (id, GWEET_ID, LIKED_BY) VALUES (3, 16, 61);
-- ... add more INSERT statements here

